# Generated by Django 4.0.6 on 2022-07-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glenn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentgrocerylist',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentgrocerylist',
            name='usual',
            field=models.BooleanField(default=False),
        ),
    ]
