# Generated by Django 4.0.6 on 2022-07-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glenn', '0002_currentgrocerylist_complete_currentgrocerylist_usual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritegrocerylist',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='favoritegrocerylist',
            name='item_note',
        ),
        migrations.AddField(
            model_name='favoritegrocerylist',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FavoriteGroceryListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('item_note', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glenn.favoritegrocerylist')),
            ],
        ),
    ]
