# Generated by Django 4.0.6 on 2022-07-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glenn', '0003_remove_favoritegrocerylist_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritegrocerylistitems',
            name='list_name',
        ),
    ]
