# Generated by Django 4.0.6 on 2022-07-28 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glenn', '0004_remove_favoritegrocerylistitems_list_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='Current List', max_length=200)),
                ('owner', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('store_location_id', models.IntegerField(blank=True, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('aisle', models.IntegerField(default=0)),
                ('usual', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('item_note', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glenn.grocerylist')),
            ],
        ),
        migrations.RemoveField(
            model_name='favoritegrocerylist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='favoritegrocerylistitems',
            name='list_id',
        ),
        migrations.DeleteModel(
            name='CurrentGroceryList',
        ),
        migrations.DeleteModel(
            name='FavoriteGroceryList',
        ),
        migrations.DeleteModel(
            name='FavoriteGroceryListItems',
        ),
    ]
