# Generated by Django 4.0.6 on 2022-08-01 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glenn', '0007_alter_grocerylistitems_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
