# Generated by Django 4.0.6 on 2022-08-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glenn', '0008_alter_grocerylist_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocerylistitems',
            options={'ordering': ['aisle']},
        ),
    ]
